name: jfmdigitalworks
recipe: drupal10
config:
  webroot: web
  php: '8.3'
services:
  database:
    type: mariadb:10.11
  appserver:
    type: php:8.3
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/web --uri=https://${LANDO_APP_NAME}.lndo.site "$@"
